---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 24597.
--- DateTime: 2024/10/9 10:40
---

-- 获取锁中的线程标识 get key
local id = redis.call('get', KEYS[1])
-- 比较线程标识与锁中标识是否一致
if(id == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del', KEYS[1])
end
return 0